gazebosim/gz-utils

- test/integration/implptr/CMakeLists.txt
This is a minor cmake change that uses `target_link_libraries` instead of `set_target_properties`. It's a minor suggestion I thought of after #1 was merged.
> implptr test: link to project library

- Changelog.md
Preparation for a prerelelase; the version number is already `1.0.0~pre1`
> Changelog for 1.0.0~pre1

- CMakeLists.txt
- Changelog.md
Branch `ign-utils1` has been created for the Edifice release and 1.0.0 released from that.
The `main` branch now corresponds to version 2.0.0~pre1, and nightlies will soon be created from this branch.
https://github.com/ignition-tooling/release-tools/issues/421
> Bump main to 2.0.0~pre1

- BUILD.bazel
Correctly exports headers and adds unit tests.
Signed-off-by: Michael Carroll <michael@openrobotics.org>
> More complete bazel implementation

- examples/using_cli/CMakeLists.txt
- examples/using_cli/main.cc
Shows basic usage in CMakeLists to build and link against the CLI11 wrapper in ignition
To test with the vendored CLI11 version, build a colcon workspace with ign-utils and ign-cmake with
```
"-DIGN_UTILS_VENDOR_CLI11:BOOL=ON"
```
and then build the example program.
To test with the system CLI11 version, build a colcon workspace with ign-utils and ign-cmake with 
```
"-DIGN_UTILS_VENDOR_CLI11:BOOL=ON"
```
and then build the example program.
> Add an example program using CLI11

- include/ignition/utils/NeverDestroyed.hh
- src/NeverDestroyed_TEST.cc
Useful for function-local static variables that are not trivially destructable.  This can be used to clean up "possible leak" warnings from memory-checking tools.
Originally imported from drake codebase (BSD 3-clause).  It has been updated for consistency with ignition codebase.
Added in support of https://github.com/ignitionrobotics/ign-math/issues/269 at the suggestion of @jwnimmer-tri (https://github.com/ignitionrobotics/ign-math/issues/269#issuecomment-975809753)
Unit tests have been imported as well
> Add NeverDestroyed utility class

- include/ignition/utils/ExtraTestMacros.hh
- include/ignition/utils/detail/ExtraTestMacros.hh
It's sort of strange to store these in ign-cmake, especially in a folder called utilities.
Ideally they can be eventually deprecated and removed from ign-cmake, but that may take a few cycles.
> Move ExtraTestMacros from ign-cmake

- src/Environment.cc
Fixes #36
For some reason clang6 doesn't pick up the inline namespace when defining functions with their fully qualified name (sans the inline namespace). This fixes the issue by defining the functions inside the inline namespace.
> Fix inline namespace issue with clang6

- .github/workflows/ci.yml
Argument to enable cpplint was incorrect
Enable cpplint
> Enable cpplint (fix argument name in ci.yml)

- .github/workflows/ci.yml
- README.md
- tutorials/installation.md
* See https://github.com/ignition-tooling/release-tools/issues/597
There are no plans to include `ign-utils2` on Garden, but whenever it's officially released, it won't have Bionic support.
No Bionic builds should be triggered.
🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸
> Remove Bionic from future releases (Garden+)

- cli/include/CMakeLists.txt
- cli/include/ignition/utils/CMakeLists.txt
- cli/include/ignition/utils/cli/IgnitionFormatter.hpp
- cli/src/CMakeLists.txt
- cli/src/cli_TEST.cc
Add a custom formatter to make standalone executables line up more closely with the previous ruby-style documentation.
Address #42 
Example result with `ign-transport-topic`: (https://github.com/ignitionrobotics/ign-transport/pull/296)
With custom formatter
```
./bin/ign-transport-topic
Introspect Ignition topics
Usage: ./bin/ign-transport-topic [OPTIONS]
Options:
-h [--help]                 Print this help message and exit
-v [--version]              
-t [--topic] TEXT           Name of a topic
Required by: --pub
Required by: --echo
Required by: --info
-m [--msgtype] TEXT         Type of message to publish
Required by: --pub
-d [--duration] FLOAT       Duration (seconds) to run
Excludes: --num
-n [--num] INT              Numer of messages to echo and then exit
Excludes: --duration …
```
> Custom cli formatter

- src/NeverDestroyed_TEST.cc
- test/CMakeLists.txt
I noticed that Windows is more strict about conversions.
It would be nice to turn on "-Wconversion" up the stack, but gcc is even _more_ strict about conversions.  This is a step in fixing that.
> Improvements to enable "-Wconversion"

- .github/ci/packages.apt
- CMakeLists.txt
- examples/using_cli/CMakeLists.txt
See https://github.com/ignition-tooling/release-tools/issues/685
> Bumps in garden : ign-cmake3, ign-utils2

- cli/src/cli_TEST.cc
- src/Environment.cc
- src/Environment_TEST.cc
- src/NeverDestroyed_TEST.cc
- test/integration/implptr/ImplPtr_TEST.cc
- test/integration/implptr/implptr_test_classes.hh
Part of https://github.com/gazebo-tooling/release-tools/issues/711, follow-up to #52
The ignition headers have been migrated to `include/gz/`, and this converts the remaining `#include <ignition/*>` statements to `#include <gz/*>`.
> Convert remaining #include statements to use gz/

- cli/src/cli_TEST.cc
Fixes compatibility with CLI11 2.0
If `IGN_UTILS_VENDOR_CLI11` is set to OFF and `CLI11` >= 2.0 was used, the compilation failed with:
~~~
2022-05-13T06:56:23.1223336Z [ 87%] Building CXX object cli/src/CMakeFiles/UNIT_cli_TEST.dir/cli_TEST.cc.o
2022-05-13T06:56:25.1811635Z /home/conda/feedstock_root/build_artifacts/libignition-utils1_1652424878233/work/cli/src/cli_TEST.cc: In function 'std::shared_ptr<TestOptions> addFlags(CLI::App&)':
2022-05-13T06:56:25.1816895Z /home/conda/feedstock_root/build_artifacts/libignition-utils1_1652424878233/work/cli/src/cli_TEST.cc:89:40: error: no matching function for call to 'CLI::App::add_option(const char [16], float&, const char [26], bool)'
2022-05-13T06:56:25.1817859Z    89 |       "Option with default value", true);
2022-05-13T06:56:25.1818289Z …
> cli_TEST: Fix compatibility with CLI11 2.0

- CMakeLists.txt
- Changelog.md
- Migration.md
- README.md
- api.md.in
- tutorials.md.in
- tutorials/installation.md
See: https://github.com/gazebo-tooling/release-tools/issues/757
> ign -> gz Partial Docs Migration and Project Name Followups : gz-utils

- include/gz/utils/ExtraTestMacros.hh
- include/gz/utils/detail/ExtraTestMacros.hh
Fixes https://github.com/gazebosim/gz-transport/pull/336
When working on https://github.com/gazebosim/gz-transport/pull/336, I noticed that we don't have the full set of macros for enabling/disabling tests on a per-platform basis.  These may not all get used, but it at least completes the set.
> Implement ExtraTestMacros for all platforms

- coverage.ignore.in
Port `ign-utils1 ` ➡️  `main`
Branch comparision: https://github.com/ignitionrobotics/ign-utils/compare/main...ign-utils1
> Merge ign-utils1 ➡️  main

- src/CMakeLists.txt
Fixes `.pc` file (see https://github.com/osrf/homebrew-simulation/pull/2016#issuecomment-1232130214)
We used to use a `c++standard` cmake variable, but recently changed to using `CMAKE_CXX_STANDARD` but hadn't updated the `CXX_STANDARD` argument to `gz_create_core_library`. This caused a `pkg-config` compilation test to fail during a brew bottle build, but it should be fixed now.
Confirm by checking for a `-std=c++17` flag in the output of `pkg-config --cflags gz-utils2`.
> Fix CXX_STANDARD in core library

- CMakeLists.txt
- Changelog.md
Signed-off-by: Nate Koenig <nate@openrobotics.org>
Preparation for 1.5.0 release.
Comparison to 1.4.1: https://github.com/gazebosim/gz-utils/compare/ignition-utils1_1.4.1...ign-utils1
Needed by future SDF PRs.
> 1.5.0 release

- include/gz/utils/ImplPtr.hh
- include/gz/utils/NeverDestroyed.hh
Fixes some gz headers
The `gz/utils/*.hh` headers on `ign-utils1` that use the `ignition` namespace need to include `gz/utils/config.hh` to get the `gz` namespace. I found this while trying to use `gz::utils::ImplPtr` in sdformat12:
* https://github.com/gazebosim/sdformat/actions/runs/3681027316/jobs/6227265470#step:8:88
> Add missing config.hh include to gz headers

- include/gz/utils/Subprocess.hh
- include/gz/utils/detail/subprocess.h
- test/integration/CMakeLists.txt
- test/integration/subprocess/subprocess_main.cc
- test/integration/subprocess_TEST.cc
This includes the unlicensed header-only `subprocess.h` from https://github.com/sheredom/subprocess.h
This gives a uniform, cross-platform way of spawning executables and interacting with them from a C++ application.  Importantly, it allows for reading both cout and cerr.
The intention is to use this to remove any custom executable calling that we have throughout the remainder of the Gazebo stack.
> Add a utility for spawning subprocesses

- include/gz/utils/ExtraTestMacros.hh
- include/gz/utils/detail/ExtraTestMacros.hh
Closes #82 
Adds macros for enabling/disabling tests based on ARM32/ARM64 platforms.
> Extra test macros for ARM32/ARM64

- tutorials/installation.md
This fixes rendering issues in the installation page and applies `mdformat`
https://gazebosim.org/api/utils/2/install.html
> Clean up installation markdown to address render issues

- .github/workflows/ci.yml
Disable 20.04 GitHub workflow on main since Harmonic is already not supporting 20.04
> ci.yml: disable 20.04 workflow

- .github/ci/packages.apt
- CMakeLists.txt
See https://github.com/gazebo-tooling/release-tools/issues/1027
> Bumps in ionic: use gz-cmake4

- BUILD.bazel
- cli/include/gz/utils/cli/GzFormatter.hpp
- src/Environment.cc
- src/Environment_TEST.cc
- src/NeverDestroyed_TEST.cc
- test/integration/implptr/ImplPtr_TEST.cc
- test/integration/implptr/implptr_test_classes.cc
- test/integration/implptr/implptr_test_classes.hh
Will also bump subprocess.h when this lands: https://github.com/sheredom/subprocess.h/pull/75
> Clang-tidy and include-what-you-use warnings

- include/gz/utils/Environment.hh
- src/Environment.cc
- src/Environment_TEST.cc
This adds functions for using collections with the environment.  It allows for conveniently retreiving and setting the environment variables via a map, rather than individually.
This also adds a clearenv and printenv for completeness.
> Add new functions for manipulating the environment

- .github/workflows/ci.yml
- .github/workflows/triage.yml
Port `ign-util1 ` ➡️  `gz-utils2`
Branch comparison: https://github.com/gazebosim/gz-utils/compare/gz-utils2...ign-util1
> Merge ign-util1 ➡️  gz-utils2

- include/gz/utils/detail/subprocess.h
- src/Environment.cc
Misspelled words, missing header, and small optimization to remove inadvertent copies.
> Minor lint feedback

- BUILD.bazel
When subprocess functionality was introduced, it wasn't tested with bazel builds.  This fixes that.
> bazel: build and test subprocess functionality

- .github/workflows/ci.yml
Attempting to enable CI on 24.04, similar to https://github.com/gazebosim/gz-math/pull/587
Adds a workflow using the noble branch of `gazebo-tooling/action-gz-ci`. Also switches to `actions/checkout@v4`.
Observe the CI results.
> Enable 24.04 CI

- CMakeLists.txt
- examples/using_cli/CMakeLists.txt
Part of https://github.com/gazebosim/gz-cmake/issues/350.
This increases our minimum required cmake version to 3.22.1 since we are already requiring that in gz-cmake4.
Check that CI is successful.
> Require cmake version 3.22.1

- CMakeLists.txt
- Changelog.md
Part of https://github.com/gazebo-tooling/release-tools/issues/1092
Comparison to 2.2.0: https://github.com/gazebosim/gz-utils/compare/gz-utils2_2.2.0...main
> Update changelog and prepare for prereleases

- log/src/Logger.cc
Fixes the following issues:
* No need to register logger, it happens automatically.
* No EOL by default when logging.
* Avoid crash on shutdown. See https://github.com/gazebosim/gz-common/pull/615
> Logger updates

- CMakeLists.txt
- Changelog.md
Preparation for 3.0.0~pre2 release.
Comparison to 3.0.0-pre1: https://github.com/gazebosim/gz-utils/compare/gz-utils3_3.0.0-pre1...prep_3.0.0pre2
> Prepare for 3.0.0~pre2 release

- log/include/gz/utils/log/Logger.hh
- log/src/Logger.cc
Fixes #<NUMBER>
The severity level of the file sink is now set to trace so that it logs to file regardless of the severity level of the console.
This patch also adds an API to set the severity level of just the console sink.
> Use common formatter for console and file sinks

- log/src/Logger.cc
The logger level change is needed because the file sink's level is `trace` and apparently `spdlog` will use the lower severity level of the logger and the sink.
The `flush_on` change is needed to cause spdlog to write to file more frequently.
> Update logger level and flush_on values

- log/src/Logger.cc
Fixes https://github.com/gazebosim/gz-common/issues/631
Based on formatting wiki https://github.com/gabime/spdlog/wiki/3.-Custom-formatting %s is for Basename of the source file and %# is for line number.
> Include file name in log format

- log/src/Logger.cc
Fixes https://github.com/gazebosim/gazebo_test_cases/issues/1701
Catches exception if the provided path could not be created. Also see https://github.com/gazebosim/gz-sim/pull/2589
> Catch spdlog exception thrown when creating file

- examples/log/main.cc
This patch:
1. Adds newlines to the logging messages used in the log example.
2. Uses `SetConsoleSinkLevel()` to only change the verbosity level of the console.
This is the result we should see in the console:
```
(2024-09-22 20:41:34.090) [info] [:] info
(2024-09-22 20:41:34.090) [warning] [:] warn
(2024-09-22 20:41:34.090) [error] [:] error
(2024-09-22 20:41:34.090) [critical] [:] critical
```
And this is the result we should see in `/tmp/my_log.txt`:
```
(2024-09-22 20:41:34.090) [trace] [:] trace
(2024-09-22 20:41:34.090) [info] [:] info
(2024-09-22 20:41:34.090) [warning] [:] warn
(2024-09-22 20:41:34.090) [error] [:] error
(2024-09-22 20:41:34.090) [critical] [:] critical
```
If we change the verbosity level using the original call …
> Add EoL and use SetConsoleSinkLevel

- log/src/Logger_TEST.cc
Adds a new unit test for the `Logger` class.
> Adding a Logger unit test

- CMakeLists.txt
- Changelog.md
- examples/log/CMakeLists.txt
- examples/using_cli/CMakeLists.txt
- package.xml
Bump main to gz-utils 4.0.0~pre1
> Bump main to gz-utils 4.0.0~pre1

- test/integration/subprocess_TEST.cc
Minor improvements to `INTEGRATION_subprocess_TEST`
This adds expectations to the subprocess test instead of just checking that cout/cerr are not empty. It also adds streaming of variable values if expectations fail.
> Add expectations to subprocess test

- BUILD.bazel
- include/gz/utils/ExtraTestMacros.hh
- src/ExtraTestMacros_TEST.cc
It was overlooked as a header-only library
> Add ExtraTestMacros target

- .github/ci/packages.apt
- CMakeLists.txt
- Migration.md
- cli/src/cli_TEST.cc
Part of https://github.com/gazebosim/gz-utils/issues/135
CLI11 is available upstream, so don't vendor by default.
> Disable CLI11 vendoring by default

- .github/workflows/ci.yml
- tutorials/installation.md
Part of https://github.com/gazebo-tooling/release-tools/issues/1222
Jammy isn't officially supported for Ionic, so move doxygen check to use Noble.
Verify that CI passes
> Use 24.04 for doxygen CI

- include/gz/utils/detail/ExtraTestMacros.hh
Fixes include in detail header
The SuppressWarning [header file](https://github.com/gazebosim/gz-utils/blob/gz-utils3_3.1.1/include/gz/utils/SuppressWarning.hh#L21) and [detail header file](https://github.com/gazebosim/gz-utils/blob/gz-utils3_3.1.1/include/gz/utils/detail/SuppressWarning.hh#L21) include each other, but for some reason the
detail/ExtraTestMacros.hh header file includes
SuppressWarning.hh. It's probably a typo, so change it to include the related header.
> Fix include in ExtraTestMacros.hh

- package.xml
Follow up to #167.
Since we now search for `cli11` as a system dependency by default, add `cli11` as a dependency in `package.xml` to aid in resolving dependencies via rosdep.
> package.xml: depend on cli11

- CMakeLists.txt
- Migration.md
Part of https://github.com/gazebosim/gz-sim/issues/2918.
This redisables vending of cli11 by reverting commit bdcef68a8bb0273d79bfbfabd9db83b82d68ddbd (#178).
> Re-disable vendoring of cli11 by default

- .github/ci/packages.apt
Prototype of an alternative approach to https://github.com/gazebo-tooling/release-tools/issues/1326.
Use unversioned `gz-jetty-*` package names in `packages.apt` file.
Verify that CI passes
Generated-by: Remove this if GenAI was not used.
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` and `Generated-by` messages.
> packages.apt: use jetty package name

- .github/workflows/bazel.yml
Update bazel ci so it runs against gz-utils4 branch
Generated-by: Remove this if GenAI was not used.
**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` and `Generated-by` messages.
> [Bazel] Enable github actions for gz-utils4
