gazebosim/gz-utils

- CMakeLists.txt
Let's go full stable on Edifice.
> First stable release will be 1.0.0

- .github/workflows/ci.yml
Part of  https://github.com/ignition-tooling/release-tools/issues/416
Update all usage of `master`
> Master branch updates

- CMakeLists.txt
- Changelog.md
Preparation for 1.0.0~pre2 release.
Comparison to 1.0.0~pre1: https://github.com/ignitionrobotics/ign-utils/compare/ignition-utils1_1.0.0-pre1...main
> 🎈 1.0.0~pre2

- bitbucket-pipelines.yml
Fixes https://github.com/ignition-tooling/release-tools/issues/203
This will make CI default to Bionic and shouldn't change anything about CI for all release branches, which are already using Bionic.
🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸
https://github.com/osrf/buildfarmer/issues/224
> 👩‍🌾 Remove bitbucket-pipelines.yml

- CMakeLists.txt
- Changelog.md
- Bump version to 1.1.0
- Update Changelog
> Prepare for version 1.1.0

- .github/workflows/ci.yml
- include/ignition/utils/ImplPtr.hh
- include/ignition/utils/NeverDestroyed.hh
Docs should always be checked now.
See if Focal CI comes back green. Or try it locally:
```
make doc 
bash <(curl -s https://raw.githubusercontent.com/ignitionrobotics/ign-cmake/ign-cmake2/tools/doc_check.sh)
```
🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸
> Add doxygen linters

- test/integration/implptr/ImplPtr_TEST.cc
Signed-off-by: Michael Carroll <michael@openrobotics.org>
> 🧹 Drop all main functions from gtest files

- cli/include/vendored-cli/ignition/utils/cli/FormatterFwd.hpp
Without this header, the project might not compile is some environments.
> Include <functional> in FormatterFwd

- BUILD.bazel
- CMakeLists.txt
- cli/BUILD.bazel
- examples/using_cli/CMakeLists.txt
- examples/using_cli/main.cc
- test/integration/implptr/CMakeLists.txt
* See https://github.com/ignition-tooling/release-tools/issues/718
* Needs https://github.com/ignitionrobotics/ign-cmake/pull/244
> Rename CMake project to gz

- cli/include/vendored-cli/gz/utils/cli/FormatterFwd.hpp
- cli/src/cli_TEST.cc
Port `ign-utils1 ` ➡️  `main`
Branch comparision: https://github.com/ignitionrobotics/ign-utils/compare/main...ign-utils1
> Merge ign-utils1 ➡️  main

- Migration.md
- cli/include/gz/utils/cli/GzFormatter.hpp
- cli/src/cli_TEST.cc
See: https://github.com/gazebo-tooling/release-tools/issues/767
> ign -> gz Provisional Finale: Source Migration : gz-utils

- CMakeLists.txt
Preparation for 2.0.0~pre2 release.
Comparison to 2.0.0~pre1: https://github.com/gazebosim/gz-utils/compare/gz-utils2_2.0.0-pre1...gz-utils2
> 🎈 2.0.0~pre2

- README.md
- tutorials/installation.md
Signed-off-by: ahcorde <ahcorde@gmail.com>
Added  install instructions for mac and windows.
[Live link is broken](https://gazebosim.org/api/utils/2.0/install.html)
> Improved install instructions gz-utils2

- CMakeLists.txt
Signed-off-by: Nate Koenig <nate@openrobotics.org>
Preparation for 2.0.0 release.
Change log was updated in #79.
> 2.0.0 release

- CMakeLists.txt
- Changelog.md
Signed-off-by: Nate Koenig <nate@openrobotics.org>
Preparation for 1.4.1 release.
Comparison to 1.4.1: https://github.com/gazebosim/gz-utils/compare/ignition-utils1_1.4.0...ign-utils1
> 1.4.1 release

- .github/workflows/ci.yml
- Changelog.md
- README.md
- include/ignition/utils/Environment.hh
- include/ignition/utils/NeverDestroyed.hh
- src/NeverDestroyed_TEST.cc
Port `ign-utils1 ` ➡️  `gz-utils2`
Branch comparison: https://github.com/ignitionrobotics/ign-utils/compare/gz-utils2...ign-utils1
> Merge ign-utils1 ➡️  gz-utils2

- CMakeLists.txt
- Changelog.md
Preparation for 1.5.1 release.
Comparison to 1.5.0: https://github.com/ignitionrobotics/ign-utils/compare/ignition-utils1_1.5.0...ign-utils1
Needed by <PR(s)>
> Prepare for 1.5.1 Release

- .github/workflows/ci.yml
- CMakeLists.txt
- Changelog.md
- README.md
- include/ignition/utils/Environment.hh
- include/ignition/utils/NeverDestroyed.hh
- src/CMakeLists.txt
- src/NeverDestroyed_TEST.cc
- tutorials/installation.md
Port `gz-utils2 ` ➡️  `main`
Branch comparison: https://github.com/ignitionrobotics/ign-utils/compare/main...gz-utils2
> Merge gz-utils2 ➡️  main

- README.md
Fixes https://github.com/gazebosim/gazebo_test_cases/issues/437
Update documentation
> Update README.md and fixed links

- .github/workflows/package_xml.yml
Follow-up to #125.
Copied from gazebosim/gz-math#581.
> Add workflow to check package.xml

- README.md
This is also being used to test https://github.com/gazebo-tooling/gzdev/pull/88
> Update badge to noble

- README.md
Part of https://github.com/gazebo-tooling/release-tools/issues/1092
> Update badges to point to gz-utils3 branch

- CMakeLists.txt
- Changelog.md
Preparation for 3.0.0~pre3 release.
Comparison to 3.0.0-pre2: https://github.com/gazebosim/gz-utils/compare/gz-utils3_3.0.0-pre2...prep_3.0.0pre3
> Prepare for 3.0.0pre3

- CMakeLists.txt
- Changelog.md
Preparation for 3.0.0 release.
Comparison to 3.0.0-pre3: https://github.com/gazebosim/gz-utils/compare/gz-utils3_3.0.0-pre3...gz-utils3
Needed by <PR(s)>
> Prepare for 3.0.0 Release

- .github/workflows/bazel.yml
This was causing the job to not run to completion.
> Fix Bazel CI workflow

- Changelog.md
Port `gz-utils2 ` ➡️  `gz-utils3`
Branch comparison: https://github.com/gazebosim/gz-utils/compare/gz-utils3...gz-utils2
> Merge gz-utils2 ➡️  gz-utils3
